# Generated by Django 5.0.2 on 2024-02-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='target',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
